version: '2'

services:
  aiworker1_yolo8_tensorrt:
    build:
      context: ./
      dockerfile: Dockerfile.gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0' ]
              capabilities: [ gpu ]
    environment:
      - BACKEND_MODULE=TENSORRT
    command: gunicorn --timeout 60  -k gevent -b unix:/tmp/gunicorn.sock -w 1 --bind 0.0.0.0:2222 serve.wsgi:app
    ports:
      - "2222:2222"

  ngnix-gpu-worker:
    image: nginx:alpine
    ports:
      - "8080:8080"
    volumes:
      - ./enrtrypoint/proxy/nginx-gpu-worker.conf:/etc/nginx/nginx.conf
    depends_on:
      - aiworker1_yolo8_tensorrt
